In [ ]:
import pickle

X = pickle.load(open('/X.pkl','rb'))
y = pickle.load(open('/y.pkl','rb'))

In [ ]:
import numpy as np
X = np.array(X,dtype=object)
y = np.array(y,dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(7500, 100, 100, 3)
(2500, 100, 100, 3)
(7500,)
(2500,)


In [ ]:
from keras.models import Sequential 
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

In [ ]:
model = Sequential()

#Declaring the feature dectectors 
#64 feature Dectectors of size 3*3 with activation function as rectified linear units.
model.add(Conv2D(64,(3,3), activation = 'relu'))  

#Pooling the feature map with Maxpooling with a matrix of size 2*2
model.add(MaxPooling2D((2,2)))

#2nd Layer of the Convulution
model.add(Conv2D(64,(3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

# Flattening the convulution matrix
model.add(Flatten())

#Input layer of ANN with 128 neurons 
model.add(Dense(128,input_shape= X.shape[1:],activation = 'relu'))

#Hidden Layer
model.add(Dense(128,activation = 'relu'))

#output layer with 2 neurons
model.add(Dense(2,activation = 'softmax'))

In [ ]:
# Compiling the model mentioning the optimizer, loss function anf metrics to tune the model.
model.compile(optimizer='adam', loss = 'sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
X_train = X_train.astype('float32')
y_train = y_train.astype('float32')
X_test = X_test.astype('float32')
y_test = y_test.astype('float32')

In [ ]:
history = model.fit(X_train,y_train, epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
235/235 [==============================] - 170s 723ms/step - loss: 5.6702 - accuracy: 0.5152 - val_loss: 0.6914 - val_accuracy: 0.5168
Epoch 2/5
235/235 [==============================] - 168s 715ms/step - loss: 0.6860 - accuracy: 0.5588 - val_loss: 0.7050 - val_accuracy: 0.5292
Epoch 3/5
235/235 [==============================] - 168s 716ms/step - loss: 0.6426 - accuracy: 0.5891 - val_loss: 0.7283 - val_accuracy: 0.5452
Epoch 4/5
235/235 [==============================] - 163s 694ms/step - loss: 0.5912 - accuracy: 0.6345 - val_loss: 0.8408 - val_accuracy: 0.5248
Epoch 5/5
235/235 [==============================] - 167s 709ms/step - loss: 0.5200 - accuracy: 0.6860 - val_loss: 1.0337 - val_accuracy: 0.5364


In [ ]:
y_pred = model.predict(X_test)

In [ ]:
import tensorflow as tf

indexes = tf.argmax(y_pred, axis=1)

In [ ]:
indexes

<tf.Tensor: shape=(2500,), dtype=int64, numpy=array([0, 1, 0, ..., 0, 0, 1])>

In [ ]:
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
a = confusion_matrix(y_test, indexes)
print(a)

[[884 358]
 [801 457]]


In [ ]:
from sklearn.linear_model import LogisticRegression

X_flatten = X_train.reshape(X_train.shape[0], -1)
X_test_flatten = X_test.reshape(X_test.shape[0], -1)
print(X_flatten.shape)
print(X_test_flatten.shape)
print(y_train.shape)

(7500, 30000)
(2500, 30000)
(7500,)


In [ ]:
from sklearn import preprocessing

scaler = preprocessing.StandardScaler().fit(X_flatten)
X_scaled = scaler.transform(X_flatten)
X_test_scaled = scaler.transform(X_test_flatten)

In [ ]:
logreg = LogisticRegression(max_iter=1500)
logreg.fit(X_scaled, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(max_iter=1500)

In [ ]:
y_log_pred = logreg.predict(X_test_scaled)

In [ ]:
score = logreg.score(X_test_scaled, y_test)
print('Test Accuracy Score', score)


Test Accuracy Score 0.542


In [ ]:
from sklearn.metrics import confusion_matrix
b = confusion_matrix(y_test, y_log_pred)
print(b)

[[733 541]
 [604 622]]
